palette = 0=#F0EDE6
palette = 1=#CB3A2A
palette = 2=#14710A
palette = 3=#A36D15
palette = 4=#6570C9
palette = 5=#A314AD
palette = 6=#099F96
palette = 7=#3B3B3B
palette = 8=#635D7C
palette = 9=#D74B47
palette = 10=#198D0C
palette = 11=#9E8D1A
palette = 12=#6462C9
palette = 13=#A314D1
palette = 14=#387CD6
palette = 15=#313131
background =#F0EDE6
foreground =#3B3B3B
cursor-color =#A36D15
selection-background =#C8C3B8
selection-foreground =#000000
